In [80]:
import sys
sys.path.insert(0,'../scripts')
from pycap_for_PESTPP_MOU import postprocess_MOU, plot_pareto, prep_for_viz, create_viz_app, plot_pareto_with_scenarios
from pathlib import Path
from ipywidgets import interact, fixed
import yaml

# Read in one of the configuration files and postprocess it. 
### The `config_file` should be your `secnario_name` + `".yml"` as assigned in the `05_MOU_setup_run.ipynb` notebook.

In [81]:
d_con = ['depletion_q_baseline_0.0_1.0_0.2',  'depletion_q_Tmin10per_0.0_1.0_0.2',  'depletion_q_Tplus10per_0.0_1.0_0.2']    #1
f_con = ['fish_dollars_baseline_0.0_1.0_0.2', 'fish_dollars_Tmin10per_0.0_1.0_0.2', 'fish_dollars_Tplus10per_0.0_1.0_0.2']   #0
configs = d_con + f_con

dof = 0
i = 2
scenario_name = d_con[i] if dof else f_con[i]
config_file = scenario_name + '.yml'

with open(Path('./configurations') / config_file,'r') as ifp:
    inpars = yaml.safe_load(ifp)
inpars

{'depletion_potential_threshold': 0.2,
 'objectives': 'fish_dollars',
 'pump_lbound_fraction': 0.0,
 'pump_ubound_fraction': 1.0,
 'ref_q': 8.6,
 'run_path': '../pycap_runs/pycap_pest/run_fish_dollars_Tplus10per_0.0_1.0_0.2',
 'scenario_name': 'fish_dollars_Tplus10per_0.0_1.0_0.2'}

### Below, the `config_file` is processed, beginning the postprocessing

In [82]:
run_path = Path(inpars['run_path'])
run_name = inpars['scenario_name']
pareto_df = postprocess_MOU(run_name, run_path)

In [83]:
pareto_df

,generation,member,Total Agriculture Receipts ($),Trout Likelihood (%),nsga2_front,nsga2_crowding_distance,spea2_unconstrained_fitness,spea2_constrained_fitness,is_feasible,feasible_distance
0,0,6,12399100.0,0.508490,1,1.000000e+30,0.000024,0.000024,1,-999
1,0,13,12310700.0,0.547894,1,1.000000e+30,0.000037,0.000037,1,-999
2,0,0,12384400.0,0.521842,1,7.679850e-01,0.000038,0.000038,1,-999
3,0,18,12328000.0,0.541264,1,6.382880e-01,0.000101,0.000101,1,-999
4,0,11,12352800.0,0.526979,1,4.308400e-01,0.000067,0.000067,1,-999
...,...,...,...,...,...,...,...,...,...,...
4345,50,gen=50_member=1296_pso,12296100.0,0.563193,1,9.562360e-02,0.000051,0.000051,1,-999
4347,50,gen=50_member=1277_pso,12045800.0,0.657048,1,5.027050e-02,1.000030,1.000030,1,-999
4352,50,gen=50_member=1297_pso,12275600.0,0.572205,1,1.449810e-02,0.000066,0.000066,1,-999
4354,50,gen=50_member=1276_pso,12227200.0,0.592374,1,4.406620e-02,0.000047,0.000047,1,-999
4355,50,gen=50_member=1282_pso,12142700.0,0.628296,1,2.056180e-02,0.000088,0.000088,1,-999

### Next the evolution of the pareto frontier is plotted, over MOU iterations. Check out how the algorithm converges on a well-defined pareto tradeoff frontier

In [84]:
interact(plot_pareto,  currgen=(0,50,1), pareto_df=fixed(pareto_df));

interactive(children=(IntSlider(value=25, description='currgen', max=50), Output()), _dom_classes=('widget-int…

### Where do your scenarios line up? You can provide a list of scenarios that you ran in notebook #3 in the following function to plot a red "x" where each scenario plots up

### NOTE: This only works for the fish vs. receipts case!

In [85]:
# dollars=False
# if 'dollar' in inpars['objectives']:
#     dollars = True
# if dollars:
#     plot_pareto_with_scenarios(pareto_df, scenarios=['LPR_Single_Run','LPR_Single_Run70','LPR_Single_Run90'])

### Finally, there is an interactive plot with the pareto frontier on the left and a map of corresponding "optimal" pumping rates on the right. 

### Note - if you get an error about ports being in conflict, change the `port=4242` argument to a different number than `4242`

In [86]:
# pareto_df_final, dv_df =  prep_for_viz(pareto_df, 50, run_path, run_name, dollar_objective=dollars)
# app = create_viz_app(pareto_df_final, dv_df)
# app.run(port=4242)

### check out `pareto_df_final` and `dv_df`. What's in these datasets? What further analysis can you perform with this information?

In [87]:
dv_df.T.sample(10)

,well_1013,well_1302,well_1323,well_1486,well_1584,well_1589,well_1643,well_1683,well_1860,well_23610,...,well_93143,well_93349,well_93422,well_93423,well_93424,well_93469,well_93832,well_94302,well_94988,well_95068
gen=29_member=1067_pso,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
gen=32_member=1192_pso,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
gen=7_member=253_pso,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
gen=39_member=1460_pso,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
gen=48_member=1821_pso,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
gen=22_member=820_pso,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
gen=44_member=1653_pso,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
gen=44_member=1663_pso,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
gen=22_member=807_pso,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
gen=16_member=602_pso,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0

In [88]:
# If we want to, we can save out the pareto tradeoff objectives results to a file. 
# Just change the name below and it will be a new copy!
pareto_df_final[[pareto_df_final.columns[3],pareto_df_final.columns[2],'member']].to_csv(f'{scenario_name}_tradeoff.csv')

In [89]:
print(scenario_name)

fish_dollars_Tplus10per_0.0_1.0_0.2

In [90]:
pareto_df.columns

Index(['generation', 'member', 'Total Agriculture Receipts ($)',
       'Trout Likelihood (%)', 'nsga2_front', 'nsga2_crowding_distance',
       'spea2_unconstrained_fitness', 'spea2_constrained_fitness',
       'is_feasible', 'feasible_distance'],
      dtype='object')