In [1]:
import pandas as pd
import yaml
from pathlib import Path

In [2]:
xlsx = Path("../Inputs/LPR_Prepped_IDW.xlsx")

global_inputs = pd.read_excel(xlsx, sheet_name="Global_Inputs")
hcw_inputs = pd.read_excel(xlsx, sheet_name="HCW_Inputs")

display(global_inputs.T)
display(hcw_inputs.head())

with open(Path("../pycap_runs/pycap_base/LPR_Redux.yml"), "r") as f:
    yml = yaml.safe_load(f)

yml["project_properties"]

                                0
Transmissivity_ft2d       1700.00
Max_Trans_ft2d           60000.00
Min_Trans_ft2d             600.00
Storage_Coeff                0.12
Max_S                        0.20
Min_S                        0.05
Default_dd_days             90.00
Default_depletion_years      5.00
Default_pumping_days        90.00
Max_FractInt                 1.00
Min_FractInt                 0.00

,HCW,Well_Status,Well_Lat,Well_Long,Max Capacity,Well Type,Q_gpm,Pumping_Days
0,418,PENDING,44.443073,89.483927,1000.0,IR10,109.5,90
1,466,EXISTING,44.461175,89.493950,1350.0,PS11,315.9,330
2,467,EXISTING,44.458573,89.493973,1780.0,PS11,296.9,330
3,490,EXISTING,44.466657,89.312108,70.0,"IR10,LV20,IN31",27.7,330
4,509,EXISTING,44.520602,89.471377,65.0,"None,IR99",0.1,60

{'name': 'LPR_Redux',
 'T': 1700.0,
 'Max_T': 60000.0,
 'Min_T': 600.0,
 'S': 0.12,
 'Max_S': 0.2,
 'Min_S': 0.05,
 'Max_FracInt': 1.0,
 'Min_FracInt': 0.0,
 'default_dd_days': 90.0,
 'default_depletion_years': 5.0,
 'default_pumping_days': 90.0}